name: Java CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]  # NEU

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Maven build
        run: mvn package -DskipTests  # NEU - erstellt die JAR

      - name: JAR hochladen  # NEU
        uses: actions/upload-artifact@v4
        with:
          name: TicTacToe
          path: target/*.jar
